#!/bin/bash
# Starts munge, installs slurm.conf, then runs the SLURM daemon for this role
# in the foreground (logs go to `docker logs`).
#   entrypoint.sh slurmctld   controller
#   entrypoint.sh slurmd      compute node (NodeName = container hostname)
#   entrypoint.sh <anything>  run that command instead (debugging)
set -euo pipefail

role="${1:-slurmd}"

# slurm.conf is generated by create.sh and mounted at /config.
if [ -f /config/slurm.conf ]; then
    tr -d '\r' < /config/slurm.conf > /etc/slurm/slurm.conf
fi

mkdir -p /shared/images /shared/jobs /shared/results
chmod 1777 /shared/jobs /shared/results

# slurmd 23.11 always initialises its cgroup/v2 plugin (CgroupPlugin=disabled only
# exists from 24.05), and slurmstepd fails to start unless the cpu, cpuset and
# memory controllers are delegated to it. With IgnoreSystemd=yes it creates its
# own scope under /sys/fs/cgroup/system.slice, so do the usual "cgroup v2 in a
# container" setup: move our processes into a leaf cgroup (a cgroup with
# processes cannot delegate controllers), then enable the controllers on the
# container root and on system.slice. PID 1 (tini, compose "init: true") must
# stay in /init: slurmstepd takes the parent of PID 1's cgroup as the root.
setup_cgroup() {
    local cg=/sys/fs/cgroup c
    [ -f "$cg/cgroup.controllers" ] || return 0
    mkdir -p "$cg/init" "$cg/system.slice"
    while read -r pid; do
        echo "$pid" > "$cg/init/cgroup.procs" 2>/dev/null || true
    done < "$cg/cgroup.procs"
    for c in $(cat "$cg/cgroup.controllers"); do
        echo "+$c" > "$cg/cgroup.subtree_control" 2>/dev/null || true
        echo "+$c" > "$cg/system.slice/cgroup.subtree_control" 2>/dev/null || true
    done
    echo "entrypoint: cgroup controllers delegated: $(cat "$cg/system.slice/cgroup.subtree_control")"
}

if [ "$role" = slurmd ]; then
    setup_cgroup
fi

mkdir -p /run/munge
chown munge:munge /run/munge
runuser -u munge -- /usr/sbin/munged

# slurmctld resolves every NodeName once at start-up. Wait until Docker's DNS
# knows the node containers, or they stay unreachable until a restart.
wait_for_nodes() {
    local nodes node i
    nodes=$(sed -n 's/^NodeName=\([^ ]*\).*/\1/p' /etc/slurm/slurm.conf)
    for node in $nodes; do
        for i in $(seq 1 60); do
            getent hosts "$node" > /dev/null && break
            sleep 1
        done
        getent hosts "$node" > /dev/null || echo "entrypoint: warning: $node does not resolve" >&2
    done
}

case "$role" in
    slurmctld)
        wait_for_nodes
        exec /usr/sbin/slurmctld -D -i
        ;;
    slurmd)
        exec /usr/sbin/slurmd -D -N "$(hostname)"
        ;;
    *)
        exec "$@"
        ;;
esac
